dmt_path = 'None'
dmt_data = 'BH_RAW/{net}.{sta}.{loc}.{cha}'
output_path = 'None'
rf_data = 'RF/{net}.{sta}.{loc}.{cha}'
mout_data = 'RF_{motype}MOUT/{net}.{sta}.{loc}.{cha}'
sum_data = 'RF_SUM/{net}.{sta}.{loc}.{cha}'
